In [1]:
#import library
import pandas as pd
import numpy as np
import itertools
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
import matplotlib.pyplot as plt

In [2]:
#read csv file
df=pd.read_csv('news.csv', index_col=None)

In [3]:
df

,Unnamed: 0,title,text,label
0,8476,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,10142,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL
...,...,...,...,...
6330,4490,State Department says it can't find emails fro...,The State Department told the Republican Natio...,REAL
6331,8062,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,FAKE
6332,8622,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...,FAKE
6333,4021,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene...",REAL
6334,4330,Jeb Bush Is Suddenly Attacking Trump. Here's W...,Jeb Bush Is Suddenly Attacking Trump. Here's W...,REAL

In [4]:
#delete unused column
dataset=df.drop("Unnamed: 0",axis=1)

In [5]:
dataset

,title,text,label
0,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL
...,...,...,...
6330,State Department says it can't find emails fro...,The State Department told the Republican Natio...,REAL
6331,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,FAKE
6332,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...,FAKE
6333,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene...",REAL
6334,Jeb Bush Is Suddenly Attacking Trump. Here's W...,Jeb Bush Is Suddenly Attacking Trump. Here's W...,REAL

In [6]:
#independent Variable
x=dataset["text"]

In [7]:
#dependent Variable
y=dataset["label"]

In [9]:
#split training set,test set
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=53)

In [16]:
#preprocess the data,convert text into number
#stop_words means remove unnecessary text ex:is,was,of
hash_vectorizer =HashingVectorizer(stop_words='english',alternate_sign=False)
#Create model and give x_train as a input to given model then predict output
hash_train = hash_vectorizer.fit_transform(X_train)
print(hash_train)
#give x_test as a input to already create model
hash_test = hash_vectorizer.transform(X_test)

  (1, 26381)	0.1336306209562122
  (1, 46353)	0.1336306209562122
  (1, 76282)	0.1336306209562122
  (1, 124604)	0.1336306209562122
  (1, 271872)	0.2672612419124244
  (1, 354766)	0.1336306209562122
  (1, 355578)	0.1336306209562122
  (1, 380136)	0.2672612419124244
  (1, 399927)	0.1336306209562122
  (1, 413315)	0.2672612419124244
  (1, 421751)	0.2672612419124244
  (1, 452780)	0.1336306209562122
  (1, 506429)	0.5345224838248488
  (1, 612563)	0.1336306209562122
  (1, 615897)	0.1336306209562122
  (1, 626851)	0.1336306209562122
  (1, 639862)	0.1336306209562122
  (1, 691517)	0.1336306209562122
  (1, 740856)	0.1336306209562122
  (1, 777362)	0.2672612419124244
  (1, 798576)	0.1336306209562122
  (1, 907820)	0.2672612419124244
  (1, 1039472)	0.1336306209562122
  (2, 14361)	0.3333333333333333
  (2, 81229)	0.3333333333333333
  :	:
  (4243, 924171)	0.08478501284163323
  (4243, 934801)	0.028261670947211076
  (4243, 935153)	0.028261670947211076
  (4243, 935275)	0.028261670947211076
  (4243, 939307)	0.1130466837888443
  (4243, 946139)	0.028261670947211076
  (4243, 949760)	0.028261670947211076
  (4243, 953107)	0.028261670947211076
  (4243, 958756)	0.028261670947211076
  (4243, 958992)	0.028261670947211076
  (4243, 963256)	0.028261670947211076
  (4243, 963865)	0.028261670947211076
  (4243, 975215)	0.028261670947211076
  (4243, 982957)	0.14130835473605538
  (4243, 993015)	0.028261670947211076
  (4243, 1004174)	0.028261670947211076
  (4243, 1004879)	0.028261670947211076
  (4243, 1009763)	0.05652334189442215
  (4243, 1010115)	0.028261670947211076
  (4243, 1017691)	0.028261670947211076
  (4243, 1026684)	0.028261670947211076
  (4243, 1027460)	0.028261670947211076
  (4243, 1038430)	0.028261670947211076
  (4243, 1039483)	0.028261670947211076
  (4243, 1044795)	0.05652334189442215

In [11]:
#check whar are the function support hash_train
dir(hash_train)

['A',
 'H',
 'T',
 '__abs__',
 '__add__',
 '__array_priority__',
 '__bool__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__idiv__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__pow__',
 '__radd__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmatmul__',
 '__rmul__',
 '__round__',
 '__rsub__',
 '__rtruediv__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '_add_dense',
 '_add_sparse',
 '_arg_min_or_max',
 '_arg_min_or_max_axis',
 '_ascontainer',
 '_asfptype',
 '_asindices',
 '_binopt',
 '_bsr_container',
 '_container',
 '_coo_container',
 '_csc_container',
 '_csr_container',
 '_deduped_data',
 '_dia_container',
 '_divide',
 '_divide_sparse',
 '_dok_container',
 '_format',
 '_get_arrayXarray',
 '_get_arrayXint',
 '_get_arrayXslice',
 '_get_columnXarray',
 '_get_index_dtype',
 '_get_intXarray',
 '_get_intXint',
 '_get_intXslice',
 '_get_sliceXarray',
 '_get_sliceXint',
 '_get_sliceXslice',
 '_get_submatrix',
 '_getcol',
 '_getmaxprint',
 '_getnnz',
 '_getrow',
 '_has_canonical_format',
 '_has_sorted_indices',
 '_imag',
 '_inequality',
 '_insert_many',
 '_lil_container',
 '_major_index_fancy',
 '_major_slice',
 '_matmul_dispatch',
 '_matmul_multivector',
 '_matmul_sparse',
 '_matmul_vector',
 '_maximum_minimum',
 '_min_or_max',
 '_min_or_max_axis',
 '_minor_index_fancy',
 '_minor_reduce',
 '_minor_slice',
 '_mul_scalar',
 '_prepare_indices',
 '_process_toarray_args',
 '_raise_on_1d_array_slice',
 '_real',
 '_rmatmul_dispatch',
 '_rsub_dense',
 '_scalar_binopt',
 '_set_arrayXarray',
 '_set_arrayXarray_sparse',
 '_set_intXint',
 '_set_many',
 '_setdiag',
 '_shape',
 '_shape_as_2d',
 '_sub_dense',
 '_sub_sparse',
 '_swap',
 '_validate_indices',
 '_with_data',
 '_zero_many',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctanh',
 'argmax',
 'argmin',
 'asformat',
 'asfptype',
 'astype',
 'ceil',
 'check_format',
 'conj',
 'conjugate',
 'copy',
 'count_nonzero',
 'data',
 'deg2rad',
 'diagonal',
 'dot',
 'dtype',
 'eliminate_zeros',
 'expm1',
 'floor',
 'format',
 'getH',
 'get_shape',
 'getcol',
 'getformat',
 'getmaxprint',
 'getnnz',
 'getrow',
 'has_canonical_format',
 'has_sorted_indices',
 'imag',
 'indices',
 'indptr',
 'log1p',
 'max',
 'maximum',
 'maxprint',
 'mean',
 'min',
 'minimum',
 'multiply',
 'nanmax',
 'nanmin',
 'ndim',
 'nnz',
 'nonzero',
 'power',
 'prune',
 'rad2deg',
 'real',
 'reshape',
 'resize',
 'rint',
 'set_shape',
 'setdiag',
 'shape',
 'sign',
 'sin',
 'sinh',
 'size',
 'sort_indices',
 'sorted_indices',
 'sqrt',
 'sum',
 'sum_duplicates',
 'tan',
 'tanh',
 'toarray',
 'tobsr',
 'tocoo',
 'tocsc',
 'tocsr',
 'todense',
 'todia',
 'todok',
 'tolil',
 'trace',
 'transpose',
 'trunc']

In [17]:
print(hash_train.toarray())

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.04490133 0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]

In [18]:
#call nlp algorithm,MultinominalNavieBays
clf = MultinomialNB()
#create Model
clf.fit(hash_train, y_train)
#Make Prediction for test set
pred = clf.predict(hash_test)
#Evaluational Metrics 
#check accuracy for actual value and predicted value
score = metrics.accuracy_score(y_test, pred)
print("accuracy:   %0.3f" % score)
#Find confusion matrix
cm = metrics.confusion_matrix(y_test, pred, labels=['FAKE', 'REAL'])

accuracy:   0.853

In [19]:
from sklearn.metrics import classification_report
#Make Classification report.This problem comes under ML-Classification
report=classification_report(y_test, pred)

In [20]:
print(report)

              precision    recall  f1-score   support

        FAKE       0.96      0.73      0.83      1008
        REAL       0.79      0.97      0.87      1083

    accuracy                           0.85      2091
   macro avg       0.87      0.85      0.85      2091
weighted avg       0.87      0.85      0.85      2091

In [21]:
dataset["text"][1]

'Google Pinterest Digg Linkedin Reddit Stumbleupon Print Delicious Pocket Tumblr \nThere are two fundamental truths in this world: Paul Ryan desperately wants to be president. And Paul Ryan will never be president. Today proved it. \nIn a particularly staggering example of political cowardice, Paul Ryan re-re-re-reversed course and announced that he was back on the Trump Train after all. This was an aboutface from where he was a few weeks ago. He had previously declared he would not be supporting or defending Trump after a tape was made public in which Trump bragged about assaulting women. Suddenly, Ryan was appearing at a pro-Trump rally and boldly declaring that he already sent in his vote to make him President of the United States. It was a surreal moment. The figurehead of the Republican Party dosed himself in gasoline, got up on a stage on a chilly afternoon in Wisconsin, and lit a match. . @SpeakerRyan says he voted for @realDonaldTrump : “Republicans, it is time to come home” https://t.co/VyTT49YvoE pic.twitter.com/wCvSCg4a5I \n— ABC News Politics (@ABCPolitics) November 5, 2016 \nThe Democratic Party couldn’t have asked for a better moment of film. Ryan’s chances of ever becoming president went down to zero in an instant. In the wreckage Trump is to leave behind in his wake, those who cravenly backed his campaign will not recover. If Ryan’s career manages to limp all the way to 2020, then the DNC will have this tape locked and loaded to be used in every ad until Election Day. \nThe ringing endorsement of the man he clearly hates on a personal level speaks volumes about his own spinelessness. Ryan has postured himself as a “principled” conservative, and one uncomfortable with Trump’s unapologetic bigotry and sexism. However, when push came to shove, Paul Ryan – like many of his colleagues – turned into a sniveling appeaser. After all his lofty tak about conviction, his principles were a house of cards and collapsed with the slightest breeze. \nWhat’s especially bizarre is how close Ryan came to making it through unscathed. For months the Speaker of the House refused to comment on Trump at all. His strategy seemed to be to keep his head down, pretend Trump didn’t exist, and hope that nobody remembered what happened in 2016. Now, just days away from the election, he screwed it all up. \nIf 2016’s very ugly election has done any good it’s by exposing the utter cowardice of the Republicans who once feigned moral courage. A reality television star spit on them, hijacked their party, insulted their wives, and got every last one of them to kneel before him. What a turn of events. \nFeatured image via Twitter'

In [22]:
#select 2nd row from count_train(preprocess training set)
hash_train[[1]]

<1x1048576 sparse matrix of type '<class 'numpy.float64'>'
	with 23 stored elements in Compressed Sparse Row format>

In [ ]:
#in the above output,1 is a number of documents (row),tota lno of features(columns) 1048576,only 23  words are present
#Feature size is fixed(default or user defined)

In [23]:
#learn all unique words
hash_vectorizer = HashingVectorizer(stop_words='english',alternate_sign=False)
#convert text into number
hash_train = hash_vectorizer.fit_transform(X_train)

In [24]:
#view original data
X_train[[1]]

1    Google Pinterest Digg Linkedin Reddit Stumbleu...
Name: text, dtype: object

In [25]:
#predict the news fake or real
clf.predict(hash_train[[1]])

array(['FAKE'], dtype='<U4')